In [6]:
import numpy as np
from setMassInVrep import getMassfromSW

for i in range(8):
    mass, iner, centr = getMassfromSW('arm'+str(i))
    print(i, mass, iner, centr)
    print('\n')

0 5.539479999999999 [[ 2.15186327e-02  5.30068346e-06 -4.81433636e-06]
 [ 5.30068346e-06  7.83861890e-03 -1.41886711e-04]
 [-4.81433636e-06 -1.41886711e-04  2.86570557e-02]] [ 0.0002  -0.01453  0.01583]


1 0.69376 [[ 0.01131843  0.0029069  -0.0013844 ]
 [ 0.0029069   0.02921274 -0.00403993]
 [-0.0013844  -0.00403993  0.0353237 ]] [-0.01878 -0.07779  0.04996]


2 1.1965 [[ 0.02435806  0.00181267 -0.00314433]
 [ 0.00181267  0.01259424 -0.00398126]
 [-0.00314433 -0.00398126  0.01627345]] [-0.03378 -0.03798  0.09302]


3 4.147189999999999 [[ 6.26279213e-02 -6.34155947e-05 -1.05680952e-03]
 [-6.34155947e-05  4.54478589e-02 -1.66179636e-02]
 [-1.05680952e-03 -1.66179636e-02  2.25275904e-02]] [-0.00652 -0.08056  0.2043 ]


4 0.032979999999999995 [[ 0.38748441  0.02236307 -0.00755002]
 [ 0.02236307  0.04117575 -0.11723182]
 [-0.00755002 -0.11723182  0.34928179]] [-0.03795 -0.58928  0.19895]


5 0.02375 [[ 0.47305056  0.02502938 -0.00757199]
 [ 0.02502938  0.04118748 -0.13094569]
 [-0.00757199