### Read and print mass, inertia and center of mass of each part of robot.

In [2]:
import numpy as np
from setMassInVrep import getMassfromSW
num_links = 5

f = open('mass.txt', 'w')
for i in range(num_links):
    ms, it, ct = getMassfromSW('arm'+str(i))
    f.write(str(ms))
    f.write('\n')
    f.write(str(it.reshape(9,1)))
    f.write('\n')
    f.write(str(ct.reshape(3,1)))
    f.write('\n')
    
f.close()

In [4]:
for i in range(num_links):
    ms, it, ct = getMassfromSW('arm'+str(i))
    print('M:' , ms, '\n')
    print('Inertia:', it, '\n')
    print('Center of mass:', ct, '\n')


M: 0.15618 

Inertia: [[ 3.32368997e-04  8.56697400e-06  1.47265975e-09]
 [ 8.56697400e-06  1.48421282e-01 -4.48200794e-10]
 [ 1.47265975e-09 -4.48200794e-10  1.48435858e-01]] 

Center of mass: [3.3655e-01 1.0000e-05 0.0000e+00] 

M: 0.03126 

Inertia: [[ 1.47036148e-04  1.15163148e-08 -7.28717210e-05]
 [ 1.15163148e-08  4.06515168e-01 -0.00000000e+00]
 [-7.28717210e-05 -0.00000000e+00  4.06448357e-01]] 

Center of mass: [ 6.3709e-01 -0.0000e+00 -1.1000e-04] 

M: 0.02228 

Inertia: [[ 1.10927738e-04 -7.27823160e-05  7.63016158e-09]
 [-7.27823160e-05  4.98311700e-01  4.48833034e-10]
 [ 7.63016158e-09  4.48833034e-10  4.98368509e-01]] 

Center of mass: [ 7.0537e-01 -1.0000e-04  0.0000e+00] 

M: 0.02457 

Inertia: [[ 1.47572609e-03 -2.72679284e-04 -2.03665792e-02]
 [-2.72679284e-04  6.19937230e-01  4.25274725e-06]
 [-2.03665792e-02  4.25274725e-06  6.18507299e-01]] 

Center of mass: [ 7.8566e-01 -3.5000e-04 -2.4760e-02] 

M: 0.00663 

Inertia: [[ 6.53615385e-04  3.18291101e-04 -1.90101900