In [10]:
import numpy as np
from setMassInVrep import getMassfromSW

f = open('mass.txt', 'w')
for i in range(8):
    ms, it, ct = getMassfromSW('arm'+str(i))
    f.write(str(ms))
    f.write('\n')
    f.write(str(it.reshape(9,1)))
    f.write('\n')
    f.write(str(ct.reshape(3,1)))
    f.write('\n')
    
f.close()

In [12]:
for i in range(8):
    ms, it, ct = getMassfromSW('arm'+str(i))
    print(ms, '\n')
    print(it, '\n')
    print(ct, '\n')


5.539479999999999 

[[ 2.15186327e-02  5.30068346e-06 -4.81433636e-06]
 [ 5.30068346e-06  7.83861890e-03 -1.41886711e-04]
 [-4.81433636e-06 -1.41886711e-04  2.86570557e-02]] 

[ 0.0002  -0.01453  0.01583] 

0.69376 

[[ 0.009921    0.0026923  -0.00143028]
 [ 0.0026923   0.0294628  -0.00363116]
 [-0.00143028 -0.00363116  0.03367621]] 

[-0.01878 -0.06637  0.0524 ] 

1.1965 

[[ 0.02408103  0.00041341  0.00041604]
 [ 0.00041341  0.01193316 -0.0029831 ]
 [ 0.00041604 -0.0029831   0.0144144 ]] 

[ 0.00439 -0.02655  0.09546] 

4.147189999999999 

[[ 4.95935114e-02 -7.75239813e-05  3.83613218e-05]
 [-7.75239813e-05  3.24397241e-02 -1.11201624e-02]
 [ 3.83613218e-05 -1.11201624e-02  1.91324276e-02]] 

[ 0.00024 -0.06913  0.16963] 

0.032979999999999995 

[[ 3.75124212e-01 -1.23698908e-04  4.13168587e-05]
 [-1.23698908e-04  4.07136722e-02 -1.16369957e-01]
 [ 4.13168587e-05 -1.16369957e-01  3.34503481e-01]] 

[ 2.1000e-04 -5.7785e-01  2.0139e-01] 

0.02375 

[[ 4.59122579e-01 -7.35692632e-05  2